site_name: "beam/shift"
extra_css: ["styles.css"]
theme:
  name: material
  features:
    - navigation.expand
    - navigation.tabs
    - toc.integrate
  logo: icon.png
  favicon: icon.png
plugins:
  - search
  - roamlinks
  - mermaid2
  - minify

nav:
  - Home: index.md
  - Guides:
      - Intro: guides/intro.md
      - Advanced: guides/advanced.md
  - Reference:
      - API: reference/api.md
