site_name: "beam/shift"
extra_css: ["styles.css"]
theme:
  name: material
  features:
    - navigation.expand
    - toc.integrate
  logo: icon.png
  favicon: icon.png
  extra_javascript:
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search
  - roamlinks
  - mermaid2
  - minify
  - include_dir_to_nav:
      flat: false
      include_empty_dir : true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

nav:
  - âœ¸: index.md
  - 2100F: JEM-2100F.md